apiVersion: v1
kind: Secret
metadata:
  name: {{ include "back.fullname" . }}-secret
  labels:
    {{- include "back.labels" . | nindent 4 }}
type: Opaque
data:
  # JWT Configuration
  JWT_SECRET: {{ .Values.config.jwt.secret | b64enc | quote }}
  {{- if .Values.config.database.ssl.enabled }}
  # SSL/TLS Certificates (base64 encoded)
  {{- if .Values.config.database.ssl.ca }}
  DB_SSL_CA: {{ .Values.config.database.ssl.ca | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.database.ssl.cert }}
  DB_SSL_CERT: {{ .Values.config.database.ssl.cert | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.database.ssl.key }}
  DB_SSL_KEY: {{ .Values.config.database.ssl.key | b64enc | quote }}
  {{- end }}
  {{- end }}