apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front.fullname" . }}-config
  labels:
    {{- include "front.labels" . | nindent 4 }}
data:
  REACT_APP_API_URL: {{ .Values.config.apiUrl | quote }}
